services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=cblokkeel1@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager

  server:
    image: cblokkeel/cblokkeeldotdev:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.cblokkeel.loadbalancer.server.port=3000"
      - "traefik.http.routers.cblokkeel.rule=Host(`cblokkeel.dev`)"
      - "traefik.http.routers.cblokkeel.entrypoints=websecure"
      - "traefik.http.routers.cblokkeel.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-public"
    environment:
      NODE_ENV: production
    networks:
      - traefik-public
    deploy:
      update_config:
        order: start-first

networks:
  traefik-public:
    external: true

volumes:
  letsencrypt:

